version: "3.2"
services:
  django:
    restart: always
    container_name: primary
    build:
      context: .
      dockerfile: Dockerfile
    command : bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

  frontend:
    restart: always
    command : npm run build
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true