# Generated by Django 2.2.12 on 2021-12-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='main_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
