# Generated by Django 2.2.12 on 2021-12-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211201_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='main_color',
            field=models.CharField(default='#ad0909', max_length=7),
        ),
    ]
