# Generated by Django 2.2.12 on 2021-10-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='bold_subtle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='light_dark',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='neon_pastel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='one_many_hues',
            field=models.BooleanField(default=False),
        ),
    ]
