# Generated by Django 2.2.12 on 2021-10-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211012_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaletteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, unique=True)),
                ('base_color', models.CharField(max_length=6)),
                ('palette_list', models.TextField(max_length=150)),
            ],
        ),
    ]
