# Generated by Django 2.2.12 on 2021-10-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211028_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palettemodel',
            name='created_at',
        ),
    ]
