# Generated by Django 2.2.12 on 2021-10-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_palettemodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='created_at',
        ),
    ]
