# Generated by Django 2.2.12 on 2021-10-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_userpreferences_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palettemodel',
            name='user',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
